"""External-model adapters."""

from .helios import (
    HeliosAdapter,
    HeliosArrays,
    HeliosFixtureMetadata,
    HeliosFluxProfile,
    HeliosTPProfile,
    PINNED_HELIOS_COMMIT,
    assert_helios_bottom_first,
    flux_cgs_to_si,
    flux_si_to_cgs,
    heating_from_net_flux,
    layer_energy_increment,
    load_integrated_flux,
    load_tp_profile,
    make_fixture_metadata,
    opacity_cgs_to_si,
    opacity_si_to_cgs,
    pressure_microbar_to_pa,
    pressure_pa_to_microbar,
    simulate_helios_tp_read,
    to_canonical_interfaces,
    write_integrated_flux_stub,
    write_param_dat,
    write_tp_profile,
)
from .helios_grid import HeliosPressureGrid, build_helios_pressure_grid
from .helios_contracts import F_INT, F_IRR, GRAVITY_SI, T_INT
from .helios_opacity_table import (
    HeliosOpacityTable,
    build_table_arrays,
    interpolate_opacity_cgs,
    read_helios_opacity_hdf5,
    write_helios_opacity_hdf5,
)

__all__ = [
    "F_INT",
    "F_IRR",
    "GRAVITY_SI",
    "HeliosAdapter",
    "HeliosArrays",
    "HeliosFixtureMetadata",
    "HeliosFluxProfile",
    "HeliosOpacityTable",
    "HeliosPressureGrid",
    "HeliosTPProfile",
    "PINNED_HELIOS_COMMIT",
    "T_INT",
    "assert_helios_bottom_first",
    "build_helios_pressure_grid",
    "build_table_arrays",
    "flux_cgs_to_si",
    "flux_si_to_cgs",
    "heating_from_net_flux",
    "layer_energy_increment",
    "interpolate_opacity_cgs",
    "load_integrated_flux",
    "load_tp_profile",
    "make_fixture_metadata",
    "opacity_cgs_to_si",
    "opacity_si_to_cgs",
    "pressure_microbar_to_pa",
    "pressure_pa_to_microbar",
    "read_helios_opacity_hdf5",
    "simulate_helios_tp_read",
    "to_canonical_interfaces",
    "write_helios_opacity_hdf5",
    "write_integrated_flux_stub",
    "write_param_dat",
    "write_tp_profile",
]
