"""R0/Stage-2 reference kernel for mixing-length convection."""

from .closure import ClosureResult, mixing_length_flux
from .config import PhysicsConfig, SolverConfig
from .diagnostics import (
    ConvergenceMetrics,
    enthalpy_normalized_adiabat,
    mixing_region_labels,
    numerical_isentrope,
    piecewise_enthalpy_reference,
    reference_enthalpy_residuals,
)
from .energy import column_enthalpy_per_area
from .gravity import ConstantGravity, InverseSquareGravity
from .grid import PressureGrid, build_grid, log_pressure_edges
from .hydrostatics import HydrostaticDomainError, reconstruct_hydrostatic
from .solvers import (
    IntegrationResult,
    SolverFailure,
    TerminalStatus,
    fixed_step,
    solve_adaptive,
)
from .solvers_enthalpy import solve_adaptive_enthalpy
from .thermodynamics import (
    AnalyticIdealGasThermo,
    ConstantH2Thermo,
    EnthalpyInversionError,
    IdealH2,
    MixtureThermo,
    NASAThermo,
    ThermoDomainError,
    analytic_h2_oracle,
    h2_he_mixture,
    monatomic_helium,
)
from .opacity import (
    AnalyticGreyOpacity,
    ConstantGreyOpacity,
    PrescribedBandOpacity,
)
from .radiation import (
    DEFAULT_DIFFUSIVITY,
    STEFAN_BOLTZMANN,
    LowerFlux,
    LowerNetInternalFlux,
    LowerTemperature,
    LowerUpwardFlux,
    RadiationResult,
    SolveRoute,
    TopIrradiation,
    radiation_core,
    solve_radiation,
)
from .rce import (
    AnalyticOpacityRCESpec,
    ManufacturedRadiativeTarget,
    RCEConfig,
    RCEResult,
    RCERoute,
    RCEStepDiagnostics,
    RCETerminalStatus,
    grey_layer_optical_thickness,
    manufactured_operator_identity,
    grey_radiative_equilibrium_temperature,
    radiative_convective_initial_temperature,
    analytic_opacity_pressure_edges,
    nested_analytic_opacity_spec,
    solve_adaptive_rce,
    solve_adaptive_rce_with_prescribed_external_flux,
)
from .implicit_convection import (
    ImplicitConvectionConfig,
    ImplicitConvectionDiagnostics,
    ImplicitConvectionResult,
    assemble_dense_jacobian,
    assemble_tridiagonal_jacobian,
    provisional_support,
    require_constant_gravity,
    solve_implicit_convection,
)
from .adapters.helios import (
    HeliosAdapter,
    HeliosFixtureMetadata,
    HeliosFluxProfile,
    HeliosTPProfile,
    load_integrated_flux,
    load_tp_profile,
    make_fixture_metadata,
)
from .trace import IntegrationTrace, TraceLevel, make_trace

__all__ = [
    "AnalyticGreyOpacity",
    "AnalyticIdealGasThermo",
    "AnalyticOpacityRCESpec",
    "analytic_opacity_pressure_edges",
    "nested_analytic_opacity_spec",
    "ClosureResult",
    "ConstantGreyOpacity",
    "ConstantGravity",
    "ConstantH2Thermo",
    "ConvergenceMetrics",
    "EnthalpyInversionError",
    "HydrostaticDomainError",
    "ImplicitConvectionConfig",
    "ImplicitConvectionDiagnostics",
    "ImplicitConvectionResult",
    "HeliosAdapter",
    "HeliosFluxProfile",
    "HeliosFixtureMetadata",
    "HeliosTPProfile",
    "IdealH2",
    "IntegrationResult",
    "IntegrationTrace",
    "InverseSquareGravity",
    "MixtureThermo",
    "NASAThermo",
    "PhysicsConfig",
    "PressureGrid",
    "SolverConfig",
    "SolverFailure",
    "TerminalStatus",
    "ThermoDomainError",
    "TraceLevel",
    "analytic_h2_oracle",
    "build_grid",
    "column_enthalpy_per_area",
    "enthalpy_normalized_adiabat",
    "fixed_step",
    "h2_he_mixture",
    "LowerFlux",
    "LowerNetInternalFlux",
    "LowerTemperature",
    "LowerUpwardFlux",
    "log_pressure_edges",
    "make_trace",
    "mixing_region_labels",
    "mixing_length_flux",
    "monatomic_helium",
    "make_fixture_metadata",
    "load_integrated_flux",
    "load_tp_profile",
    "ManufacturedRadiativeTarget",
    "numerical_isentrope",
    "PrescribedBandOpacity",
    "piecewise_enthalpy_reference",
    "radiation_core",
    "RadiationResult",
    "reconstruct_hydrostatic",
    "reference_enthalpy_residuals",
    "RCEConfig",
    "RCEResult",
    "RCERoute",
    "RCEStepDiagnostics",
    "RCETerminalStatus",
    "manufactured_operator_identity",
    "grey_layer_optical_thickness",
    "grey_radiative_equilibrium_temperature",
    "radiative_convective_initial_temperature",
    "solve_adaptive",
    "solve_adaptive_rce",
    "solve_adaptive_rce_with_prescribed_external_flux",
    "solve_implicit_convection",
    "assemble_dense_jacobian",
    "assemble_tridiagonal_jacobian",
    "provisional_support",
    "require_constant_gravity",
    "solve_radiation",
    "SolveRoute",
    "STEFAN_BOLTZMANN",
    "solve_adaptive_enthalpy",
    "TopIrradiation",
]
